spring:
  datasource:
      url: jdbc:h2:mem:testdb
      username: root
      password: luke
      driverClassName: org.h2.Driver
  jpa:
      database-plataform: org.hibernate.dialect.H2Dialect
      database: h2
  h2:
      console:
          enabled: true